### PR TITLE
Add average display on review list

### PR DESCRIPTION
**Pull request by ryanmitchell**
What do you think about adding something like this?

### CODE REVIEW

**Comment by sampoyigi** [comment]
Love it! 

I'm guessing its still work in progress?

**Comment by ryanmitchell** [comment]
Yeah it probably needs styled better. Open to any suggestions!

**Comment by sampoyigi** [comment]
No no, the styling is good. Just the rating text.. Instead of numbers you can use the actual rating text (Good.. Bad) And I'll put the HTML in a separate partial and call it from the list partial.

**Comment by ryanmitchell** [comment]
No problem - both done

**Comment by sampoyigi** [comment]
Was just reviewing this again and I thought why not just use a pie chart instead of the progress bar? Since we're adding a new feature might be nice to make it look cool too ;)

**Comment by ryanmitchell** [comment]
Yep sure. Just use Chart.js from the dashboard views?

**Comment by ryanmitchell** [comment]
Ok that should be there now - just lifted the colours from dashboard for them - that probably needs looked at as there are only 3 so I've cycled over them. Never sure what colours to use to be honest.

**Comment by sampoyigi** [comment]
Made some changes

**Comment by ryanmitchell** [comment]
Looks good :)

**Review by sampoyigi — APPROVED** [review]

**Pull request merged**
