### PR TITLE
Reviews: Allow for date range, allow text in listing view

### PR DESCRIPTION
**Pull request by ryanmitchell**
A couple of minor changes to reviews on the basis of what some customers have asked for.

Some other things I'd like to do, if you are happy and can guide me a bit:

1. Give a review setting option for 'chasing' reviews, ie allow the admin to specify a time in hours after which to send a follow up email asking them to review the order (link to order page should have the review form?). Can do most of this but not sure how to do the scheduling of the chase?

2. Add the average rating on the list view above the table... see attached from Resdiary to indicate how they handle it. It means when you choose a date range you can see the average scores over that period - a nice feature. If youre happy I just need to know how to insert it (i presume in the view I add some HTML, but how do I call a method on the table list items collection?)

104130650-c2372f00-5369-11eb-87eb-4c8b9efa355f

### CODE REVIEW

**Comment by sampoyigi** [comment]
So I'm testing a time-based event with Automations. Basically, a new time trigger Event that runs every X hours on all orders or orders that meet specified conditions. With this, you can register your Automation action to send the follow-up email (similar to how SendSMSNotification action works).

You need to override the `lists/list` partial from the reviews views folder, so you can render the summary partial with access to the `$records` variable

**Comment by sampoyigi** [comment]
The time-based event https://github.com/tastyigniter/ti-ext-automation/commit/438086382490cccb6390656a31491fcf1d1d43be

**Comment by ryanmitchell** [comment]
Looks good. Just so I'm clear... do you want me to use the same approach for review chasing, or do you want me to subscribe to the `automation.order.schedule.hourly` event?

**Comment by sampoyigi** [comment]
Yup subscribe to `automation.order.schedule.hourly` event...

**Review by sampoyigi — APPROVED** [review]

**Pull request merged**
