### PR TITLE
Default userPosition for logged in user to default address if not specified

### PR DESCRIPTION
**Pull request by djtimca**
Set the default userPosition to the customer's default address when they are logged in if they haven't otherwise specified a location through the search bar.

### CODE REVIEW

**Comment by djtimca** [comment]
I think I'm close on this one, but for some reason once I've added in this additional code I am getting an error:

```
(1/1) BadMethodCallExceptionCall to undefined method Admin\Models\Locations_model::reviews_score()
--
in ForwardsCalls.php line 50
at Model::throwBadMethodCallException('reviews_score')in ForwardsCalls.php line 36
at Model->forwardCallTo(object(Builder), 'reviews_score', array())in Model.php line 1622
at Model->__call('reviews_score', array())in ExtendableTrait.php line 442


```

**Comment by djtimca** [comment]
Actually just updated to latest beta and it now appears to work as expected.

**Comment by sampoyigi** [comment]
Yea I added the feature after I saw your slack message. The feature was already requested on the forum some time ago but never got to it.

**Comment by djtimca** [comment]
Perfect - if it is there already disregard this.

**Pull request closed without merging**
