### PR TITLE
First stab at review chasing

### PR DESCRIPTION
**Pull request by ryanmitchell**

### CODE REVIEW

**Comment by sampoyigi** [comment]
This is really great!!! 

I have plans for a Reminder System and stuff like this will fit right into it perfectly... How about we sort that out first then can come back to this PR... I'll start a PR on the Reminder System after the first RC is released.

**Comment by ryanmitchell** [comment]
Sounds good. Whatever way you think it fits in.

**Comment by ryanmitchell** [comment]
Ok, I've updated this to use `automation.order.schedule.hourly` - is this what you had intended? if not let me know :)

**Comment by sampoyigi** [comment]
Erm, not what I intended.. Instead of the listener class, it would be an Automation Action class (see SendSMSNotification or SendMailNotification).. 

If you haven't, see the Automation workflow [here](https://tastyigniter.com/marketplace/item/igniter-automation) to get a glimpse of how it works.

System admins can create automation rules from their dashboard.. The `automation.order.schedule.hourly` event will be available to them as Order Schedule event which they can then use to create an automation rule with actions and/or conditions.

You also have the option of registering a preset automation rule from your extension so when the extension is installed the preset automation rule is created.. https://github.com/igniter-labs/ti-ext-smsnotify/blob/431c903ddaf6c4fbf14a9a35055f0350cfeca1b4/Extension.php#L100-L111

**Comment by ryanmitchell** [comment]
Never really looked into the automation extension - I guess now is the time to dive in :)

**Comment by ryanmitchell** [comment]
Is there anywhere a condition has been defined? Cant see any in automation or SMS notify. 

It looks like i should use the order schedule event, the sendsmail action, and a new condition that checks whether a review has been added and the time since the order. Then i just register the mail template and an automation preset with the right config.

**Comment by sampoyigi** [comment]
Yup, must nicer approach with the condition. 

Conditions are registered as Attribute classes, see https://github.com/tastyigniter/ti-ext-user/blob/c1a032e974c0bc5fd098638d74f918859cfd811b/Extension.php#L22

**Comment by sampoyigi** [comment]
I'll accept a PR to add the `time since order` attribute to the OrderAttribute condition

**Comment by ryanmitchell** [comment]
Great. And on reservations too. 

Asides from that I was thinking of a ReviewCount condition - that would make the operators make sense. Open to other suggestions on how to do it.

**Comment by ryanmitchell** [comment]
Updated, let me know if this is the sort of thing you had in mind.

**Comment by ryanmitchell** [comment]
Thanks for the change - this should work (I think!?)

**Review by sampoyigi — APPROVED** [review]

**Comment by sampoyigi** [comment]
I merged too quick, thought it was all done.. Its missing the ChaseReviews Event class 🤷‍♂️

**Comment by ryanmitchell** [comment]
My mistake - forgot to remove that subscribe. We don't need it anymore.

**Comment by ryanmitchell** [comment]
Opened a new PR here with the change as I cant push to this one now:
https://github.com/tastyigniter/ti-ext-local/pull/51

**Pull request merged**
