### PR TITLE
Ensure only categories from the location are displayed

### PR DESCRIPTION
**Pull request by ryanmitchell**

### CODE REVIEW

**Comment by sampoyigi** [comment]
Aren't we already doing this in `Menus_model::scopeListFrontEnd()`?

**Comment by ryanmitchell** [comment]
I thought so too but it wasn’t working :)

it’s not limiting it to the selected location passed anyway. This change does.

**Comment by ryanmitchell** [comment]
To explain more throughly - we are limiting menu items by location but when they are returned here is includes ALL categories associated with the menu item not just the ones for this location. So here we filter then to be only the ones for this location.

**Comment by sampoyigi** [comment]
Got it. Would prefer we do this on the DB, its much faster. You could specify a locationable query when eager loading the  `categories` relationship

**Comment by ryanmitchell** [comment]
No problem - thats been updated.

**Pull request merged**
