### PR TITLE
Fix: defaultOrderType can be disabled type

### PR DESCRIPTION
**Pull request by philipxyc**
### The problem:
1. log in as an Admin user, and disable Delivery for a location.
2. Open the menu page of this location, will see the Pickup option is not highlighted.
3. Try to add an item to the cart, will receive an error message: "Delivery is not available".

Though the solution to this problem is relatively easy, just manually click on the "Pickup" option on the page, the behavior is indeed very confusing for innocent customers.

### Future work
There is a TODO comment in Location.php, for the corner case that all order types are disabled. I currently fall back this corner case to the original behavior, which is a menu page with an invisible delivery option selected. However, the ideal solution to this case would be to display the whole menu page as "Sorry, there's no active order type for this location".

### CODE REVIEW

**Comment by sampoyigi** [comment]
Thank you for the PR. I've made some adjustments and reverted some of the changes so that we can keep the defaultOrderType component property, which is used by many users. It is similar to your logic, except that when there is no active order type, it now redirects to the home page with an error message. Let me know your thoughts.

**Comment by philipxyc** [comment]
Thanks for the modifications, Sam! They look more robust than my original change.

Regarding the no active order type case, do you think it would be better to imitate the logic for "Outside Delivery/Pickup time"? More specifically, it could be displaying a message in the _local-control_ component saying "no active order type" and grey out the checkout button.
However, this should be a pretty rare case, and what I mentioned above is just an optional suggestion. I think the current solution displaying the error message is fine, though with just one suggestion on not redirecting to the homepage. I think displaying the error message and keeping the user stay on the same page would make more sense.

I'm currently solving another bug regarding the stripe payment, and I got some thoughts about the payment integration. I'll email you later for some more details. 

Again, thank you so much for your awesome work.

**Comment by sampoyigi** [comment]
Yup, we should keep the user on the same page and simply disable the checkout button. Do you want to have a go at it?

**Comment by sampoyigi** [comment]
Thank you for the PR

**Pull request merged**
