### PR TITLE
Move to lang packs approach

### PR DESCRIPTION
**Pull request by ryanmitchell**
Reference: https://github.com/tastyigniter/TastyIgniter/pull/605

Let me know if I've got them all!

### CODE REVIEW

**Comment by sampoyigi** [comment]
Yup looks like you got the local extension covered.

**Comment by sampoyigi** [comment]
You missed removing the date format settings fields

**Comment by ryanmitchell** [comment]
In general settings in the admin panel ?

**Comment by sampoyigi** [comment]
> In general settings in the admin panel ?

Yups ;)

**Comment by ryanmitchell** [comment]
YEah I mentioned that in the main PR - do you want to remove them or deprecate them?

**Comment by sampoyigi** [comment]
Oh yea, I'm happy for you to remove them. I'll add a note in the changelog.

**Comment by ryanmitchell** [comment]
Ok, removed in the main PR. I'll work on removing the formats from other extensions over this week all going well.

**Review by sampoyigi — APPROVED** [review]

**Pull request merged**
